version: '3'
volumes:
  dados: 
services:
  db: 
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Volume para apontar para os scripts da maquina host apontando para a pasta script dentro do container.
      - ./scripts:/scripts
      # Apontar o script de inicialização sql e apontar para onde pede na documentação. https://hub.docker.com/_/postgres
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      # Site 
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    


